-- MySQL Script generated by MySQL Workbench
-- Fri May 11 11:34:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wildslack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildslack` DEFAULT CHARACTER SET utf8 ;
USE `wildslack` ;

-- -----------------------------------------------------
-- Table `wildslack`.`workspace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`workspace` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `wildslack`.`app_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`app_role`(
`id` INT NOT NULL,
`role_name` VARCHAR(50)NOT NULL,
PRIMARY KEY (`id`));
INSERT INTO app_role(id,role_name) VALUES (1,"USER");
INSERT INTO app_role values(2, "ADMIN");

-- -----------------------------------------------------
-- Table `wildslack`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`channel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NULL DEFAULT NULL,
  `default_channel` BOOLEAN,
  `id_workspace` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_workspace` ASC),
  CONSTRAINT `channel`
    FOREIGN KEY (`id_workspace`)
    REFERENCES `wildslack`.`workspace` (`id`));


-------------------------------------------------------
-- Table `wildslack`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`app_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `last_channel_id` INT ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC),
	FOREIGN KEY (`last_channel_id`)
    REFERENCES `wildslack`.`channel` (`id`));  
  



-- -----------------------------------------------------
-- Table `wildslack`.`workspace_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`workspace_member` (
  `id_app_user` INT NOT NULL,
  `id_workspace` INT NOT NULL,
  INDEX (`id_app_user` ASC),
  INDEX (`id_workspace` ASC),
  CONSTRAINT `workspace_member`
    FOREIGN KEY (`id_app_user`)
    REFERENCES `wildslack`.`app_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_workspace`)
    REFERENCES `wildslack`.`workspace` (`id`));


-- -----------------------------------------------------
-- Table `wildslack`.`channel_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`channel_manager` (
  `id_app_user` INT NOT NULL,
  `id_channel` INT NOT NULL,
  INDEX (`id_app_user` ASC),
  INDEX (`id_channel` ASC),
  CONSTRAINT `channel_manager_app_user`
    FOREIGN KEY (`id_app_user`)
    REFERENCES `wildslack`.`app_user` (`id`),
  CONSTRAINT `channel_manager`
    FOREIGN KEY (`id_channel`)
    REFERENCES `wildslack`.`channel` (`id`));


-- -----------------------------------------------------
-- Table `wildslack`.`channel_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`channel_member` (
  `id_channel` INT NOT NULL,
  `id_app_user` INT NOT NULL,
  INDEX (`id_channel` ASC),
  INDEX (`id_app_user` ASC),
  CONSTRAINT `channel_member`
    FOREIGN KEY (`id_channel`)
    REFERENCES `wildslack`.`channel` (`id`),
  CONSTRAINT `channel_member_app_user`
    FOREIGN KEY (`id_app_user`)
    REFERENCES `wildslack`.`app_user` (`id`));


-- -----------------------------------------------------
-- Table `wildslack`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `wildslack`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`post` (
  `id_app_user` INT NOT NULL,
  `id_message` INT NOT NULL,
  `id_channel` INT NOT NULL,
  INDEX (`id_app_user` ASC),
  INDEX (`id_message` ASC),
  INDEX (`id_channel` ASC),
  CONSTRAINT `post_app_user`
    FOREIGN KEY (`id_app_user`)
    REFERENCES `wildslack`.`app_user` (`id`),
  CONSTRAINT `post_message`
    FOREIGN KEY (`id_message`)
    REFERENCES `wildslack`.`message` (`id`),
  CONSTRAINT `post_channel`
    FOREIGN KEY (`id_channel`)
    REFERENCES `wildslack`.`channel` (`id`));


-- -----------------------------------------------------
-- Table `wildslack`.`workspace_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`workspace_manager` (
  `id_app_user` INT NOT NULL,
  `id_workspace` INT NOT NULL,
  INDEX (`id_app_user` ASC),
  INDEX (`id_workspace` ASC),
  CONSTRAINT `workspace_manager_app_user`
    FOREIGN KEY (`id_app_user`)
    REFERENCES `wildslack`.`app_user` (`id`),
  CONSTRAINT `workspace_manager`
    FOREIGN KEY (`id_workspace`)
    REFERENCES `wildslack`.`workspace` (`id`));




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
