-- MySQL Script generated by MySQL Workbench
-- Tue May  8 14:53:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wildslack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wildslack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildslack` DEFAULT CHARACTER SET utf8 ;
USE `wildslack` ;

-- -----------------------------------------------------
-- Table `wildslack`.`Workspace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Workspace` (
  `IDWorkspace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IDWorkspace`),
  PRIMARY KEY (`IDWorkspace`));


-- -----------------------------------------------------
-- Table `wildslack`.`Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Channel` (
  `IDChannel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(50) NULL DEFAULT NULL,
  `IDWorkspace` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDChannel`),
  INDEX (`IDWorkspace` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDWorkspace`)
    REFERENCES `wildslack`.`Workspace` (`IDWorkspace`));


-- -----------------------------------------------------
-- Table `wildslack`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`User` (
  `IDUser` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(10) NULL DEFAULT NULL,
  `pseudo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDUser`),
  PRIMARY KEY (`IDUser`));


-- -----------------------------------------------------
-- Table `wildslack`.`Membre_WorkSpace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Membre_WorkSpace` (
  `IDUser` INT NOT NULL,
  `IDWorkspace` INT NOT NULL,
  INDEX (`IDUser` ASC),
  INDEX (`IDWorkspace` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDUser`)
    REFERENCES `wildslack`.`User` (`IDUser`),
  CONSTRAINT ``
    FOREIGN KEY (`IDWorkspace`)
    REFERENCES `wildslack`.`Workspace` (`IDWorkspace`));


-- -----------------------------------------------------
-- Table `wildslack`.`Channel_Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Channel_Manager` (
  `IDUser` INT NULL DEFAULT NULL,
  `IDChannel` INT NULL DEFAULT NULL,
  INDEX (`IDUser` ASC),
  INDEX (`IDChannel` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDUser`)
    REFERENCES `wildslack`.`User` (`IDUser`),
  CONSTRAINT ``
    FOREIGN KEY (`IDChannel`)
    REFERENCES `wildslack`.`Channel` (`IDChannel`));


-- -----------------------------------------------------
-- Table `wildslack`.`Membre_Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Membre_Channel` (
  `IDChannel` INT NOT NULL,
  `IDUser` INT NOT NULL,
  INDEX (`IDChannel` ASC),
  INDEX (`IDUser` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDChannel`)
    REFERENCES `wildslack`.`Channel` (`IDChannel`),
  CONSTRAINT ``
    FOREIGN KEY (`IDUser`)
    REFERENCES `wildslack`.`User` (`IDUser`));


-- -----------------------------------------------------
-- Table `wildslack`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Message` (
  `IDmessage` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(300) NULL DEFAULT '0',
  PRIMARY KEY (`IDmessage`));


-- -----------------------------------------------------
-- Table `wildslack`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`Post` (
  `IDUser` INT NULL DEFAULT NULL,
  `IDmessage` INT NULL DEFAULT NULL,
  `IDChannel` INT NULL DEFAULT NULL,
  INDEX (`IDUser` ASC),
  INDEX (`IDmessage` ASC),
  INDEX (`IDChannel` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDUser`)
    REFERENCES `wildslack`.`User` (`IDUser`),
  CONSTRAINT ``
    FOREIGN KEY (`IDmessage`)
    REFERENCES `wildslack`.`Message` (`IDmessage`),
  CONSTRAINT ``
    FOREIGN KEY (`IDChannel`)
    REFERENCES `wildslack`.`Channel` (`IDChannel`));


-- -----------------------------------------------------
-- Table `wildslack`.`WorkSpace_Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildslack`.`WorkSpace_Manager` (
  `IDUser` INT NULL DEFAULT NULL,
  `IDWorkspace` INT NULL DEFAULT NULL,
  INDEX (`IDUser` ASC),
  INDEX (`IDWorkspace` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`IDUser`)
    REFERENCES `wildslack`.`User` (`IDUser`),
  CONSTRAINT ``
    FOREIGN KEY (`IDWorkspace`)
    REFERENCES `wildslack`.`Workspace` (`IDWorkspace`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
